### ISSUE TITLE
Revisión de Teams de MH y notificaciones

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/mozilla-hispano.org#159]
Habría que hacer una pequeña revisión a los teams que hay en Github, varios sobran o no aportan mucho. Por otro lado, en caso de necesitar feedback para un issue, ¿cual es la mejor manera de notificar a todos aquellos que colaboren en MH? ¿Mencionar a un grupo que tenga read-access en el que estemos todos?

**Comment by fjaguero** [comment]
Se notificará a el/los reponsables del proyecto a la hora de mencionar.

**Comment by KevinLoaiza** [comment]
Veo que hay varios proyectos en Backlog y únicamente este In Progress. ¿Qué sucede? Sé que es una plataforma en la que se apoya voluntariamente y todos tenemos nuestras ocupaciones. Pero, supongo al unirnos a MH, estamos haciendo un compromiso y por lo tanto se hace otra ocupación, ya sea como hobbie o pasión.  ¿No hay movimiento literal o ya están caducos los proyectos? -porque veo que los comentarios, sino años, cuentan con meses de antigüedad-.

**Comment by fjaguero** [comment]
El tema es que acabamos de pasar la vista de tareas a Waffle (que es donde se asigna la etiqueta de in-progress al mover un issue). Hay varia gente haciendo cosas de Labs aunque no sea en este proyecto (por ej. https://waffle.io/mozillahispano/openwapp).
