### ISSUE TITLE
Actualizar a Wordpress 4.0

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/mozilla-hispano.org#191]
Necesitamos actualizar a Wordpress 4.0 para aplicar los parches de seguridad correspondientes y además mejorar los actuales problemas a la hora de incrustar videos de Youtube.

**Comment by fjaguero** [comment]
Updated a 4.1

**Comment by nukeador** [comment]
Tenemos que hacer algo para que no se vuelva a repetir el tardar tanto en actualizar, al menos que sea P1 el actualizar antes que cualquier otra cosa, ya que podemos tener problemas grandes de no hacerlo.

**Comment by fjaguero** [comment]
Yo me puedo encargar de ello. Estaré al tanto de las actualizaciones pero siempre viene bien que alguien que lo use a diario notifique via Github.

**Comment by nukeador** [comment]
La gente de noticias que entra al panel más a menudo podría dar el aviso en github.

/cc @deimidis @francjp

**Comment by francjp** [comment]
La próxima hago una campaña en Kickstarter, porque creo que esta vez había avisado por varios medios y en varias ocasiones la necesidad de actualizar (como así también los plugins). De todas formas, estaré más atento.
