### ISSUE TITLE
Repasar Meta-Tags

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/mozilla-hispano.org#20]
Sólo está "<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />"

Hay que repasar por qué no existe ni el meta Title ni el Description, por ej. Con eso solucionariamos el problema de compartir en redes sociales, ya que no se comparte correctamente el título del artículo/web.

**Comment by fjaguero** [comment]
@nukeador @francjp intento acceder a la página de config del plugin y me dice que no tengo permisos

**Comment by francjp** [comment]
Me no entender... yo creo que puedo tocar los plugins para desactivarlos, por los permisos que tengo en el WP, pero se supone que es técnico quien hace estas cosas, no??

**Comment by nukeador** [comment]
@fjaguero ¿qué necesitas hacer?

**Comment by fjaguero** [comment]
Ya está funcionando tanto en home como en artículos, sacando el description y las categorías como tags. 
![Screenshot](http://cl.ly/image/2g0v1O0D3C0B/Image%202015-08-26%20at%209.57.08%20a.%20m..png)
