### ISSUE TITLE
Margen en imágenes de artículos de WordPress 

### ISSUE THREAD

**Issue by stripTM** [mozillahispano/mozilla-hispano.org#202]
Añadir un margen en las imágenes que acompañan los artículos de WordPress

**Comment by fjaguero** [comment]
En este caso, las imágenes de los artículos de wordpress (del single.php), no tienen padding correcto.

**Comment by fjaguero** [comment]
@tarefer ¿Te vas a poner con ello o lo puedo tomar? :)

**Comment by fjaguero** [comment]
@stripTM ¿Podemos reproducir este? Esoty viendo artículos y no logro reproducirlo.

**Comment by fjaguero** [comment]
Lo cierro ya que no lo logro reproducir.
