### ISSUE TITLE
Banner aviso en foro

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#206]
Hola,

Necesitamos tener un banner con un aviso en la parte superior de todas las páginas del foro.

El texto que queremos tener será:

> "A partir del dia X de Y, la asistencia de los productos Mozilla se realizara desde la plataforma de support.mozilla.org, todos los temas aquí quedarán cerrados no pudiéndose realizar más cambios."

(La fecha exacta la confirmaremos en breve)

Posteriormente a la migración el texto cambiará a:

> "Este foro se guarda como histórico y no se pueden añadir mas comentarios, si aun quieres hacer una petición de ayuda accede a [la plataforma de ayuda de Mozilla](https://support.mozilla.org), si quieres participar las discusiones y debates de la comunidad, [accede a los nuevos foros de discusion](http://foro.mozilla-hispano.org)"

**Comment by fjaguero** [comment]
@nukeador @stripTM Me lo asigno. Cuando tengas la fecha ping.

**Comment by nukeador** [comment]
Lo abrí para que podáis ir pensado en ello, pero la idea es inicios de febrero.

**Comment by fjaguero** [comment]
Ok, perfecto

**Comment by nukeador** [comment]
La fecha será el 10 de febrero.

¿Podemos poner el aviso ASAP?

Gracias.
