### ISSUE TITLE
Añadir dominio en enlaces del menú de los nuevos foros

### ISSUE THREAD

**Issue by stripTM** [mozillahispano/mozilla-hispano.org#207]
El menú no está pensado para múltiples subdominios y cuando estamos dentro de foros.mozilla-hispano.org no enlaza correctamente, ej.

```html
<li><a href="/foro/" title="Foro de asistencia técnica">Foro de asistencia</a></li>
<li><a href="/documentacion/" title="Documentos, artículos y preguntas frecuentes de ayuda a los usuarios">Documentación</a></li>
<li><a href="/documentacion/Asistencia" title="Proyectos">Proyectos</a></li>
```

**Comment by voylinux** [comment]
Si hay mucho marrones de este tipo por tener diferentes aplicaciones igual se podría añadir un YAML o algún archivo para la config del que se lean variables de entorno o similar. Para no tener que 'harcodear'.

**Comment by fjaguero** [comment]
@stripTM ¿donde está ese código?
@voylinux Sí, sería lo suyo organizarlo

**Comment by stripTM** [comment]
Pues es que el código se debe guardar en base de datos, se gestiona desde el propio administrador de Discourse: Administración, personalizar, css/html y allí en el epígrafe Encabezado.
Cambié las urls para que ahora sean (podéis probarlo)
```html
<ul class="submenu">
	<li><a href="//www.mozilla-hispano.org/foro/" title="Foro de asistencia técnica">Foro de asistencia</a></li>
	<li><a href="//www.mozilla-hispano.org/documentacion/" title="Documentos, artículos y preguntas frecuentes de ayuda a los usuarios">Documentación</a></li>
	<li><a href="//www.mozilla-hispano.org/documentacion/Asistencia" title="Proyectos">Proyectos</a></li>
</ul>
```

Creo que merece la pena investigar si esto se puede gestionar de alguna manera que no tengamos que acordarnos cuando cambiemos la cabecera en mozilla-hispano.org que también hay que cambiarlo aquí.

**Comment by nukeador** [comment]
Se puede cargandolo con un js de forma dinámica, que se que no te gusta nada :P

**Comment by fjaguero** [comment]
¿Esto cómo quedó?

**Comment by stripTM** [comment]
La cabecera se gestiona desde el panel de administración de Discourse, si la cambiamos en la web hay que acordarse de cambiarla también aquí.

**Comment by nukeador** [comment]
Esto está solucionado ¿no?
