### ISSUE TITLE
[Discourse] Tamaño de la letra

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#213]
El tamaño de la letra de Discourse me sigue pareciendo demasiado pequeña en comparación con el resto de secciones.

**Comment by stripTM** [comment]
Si que es pequeño ¿Que te parece poner el en body 0.7em en lugar de los 0.62em actuales?

**Comment by nukeador** [comment]
¿El body o html no debería tener una base en tamaño fijo (px) para evitar problemas con el tamaño fijo que cada navegador define por defecto?

**Comment by stripTM** [comment]
A mi me gusta dejarlo abierto, así si estás cegarruto tendrás el tamaño de letra grande y luego el resto ya va proporcional respecto al tamaño que tienes por defecto.

**Comment by nukeador** [comment]
El tamaño base debería ser 14px, con el tamaño por defecto todo lo que esté por debajo de 1em se ve diminuto en resoluciones grandes.

Además el tamaño de la letra del pie no coincide con el resto del portal.

**Comment by nukeador** [comment]
Ahora mismo el problema redise en que:

html define font-size: 14px;
body define font-size: 0.62em;
main define font-size: 1.4em;

El resultado en que tenemos un font-size computado de 12,15px en los mensajes normales lo cual es muy pequeño, y en muchos mensajes que son más pequeños es diminuto.

Un fix rápido sería poner en main el font-size a 1.6em, pero creo que lo mejor es solucionar el entuerto de base para que no haya estos bailes de tamaños.

Normalmente el html debería tener 0.875rem.

**Comment by stripTM** [comment]
Creo que metiendole esto queda bastante bien:
.container {
        font-size: 1.2em;
}

**Comment by nukeador** [comment]
Esto ya está fixed en prod, ¿no?
