### ISSUE TITLE
Aviso en el foro

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#229]
Hola,

Mañana martes 10, tenemos que poner el aviso definitivo en todas las páginas del foro:

> "Este foro se guarda como histórico y no se pueden añadir mas comentarios, si aun quieres hacer una petición de ayuda accede a [la plataforma de ayuda de Mozilla](https://support.mozilla.org), si quieres participar las discusiones y debates de la comunidad, [accede a los nuevos foros de discusion](http://foro.mozilla-hispano.org)"

Tiene que ser un mensaje muy visible. Debería estar aplicado a las 18UTC una vez se confirme que los foros de SUMO está activados.

**Comment by fjaguero** [comment]
Yo no podré a las 18UTC, si no al menos 2-3 horas más tarde.

**Comment by fjaguero** [comment]
Entiendo que lo de muy visible es la misma barra pero más destacada :+1:

**Comment by nukeador** [comment]
Metí temporalmente el aviso donde estaba antes enlazando a SUMO, luego le dais el nuevo enfoque que queráis con el mismo mensaje.

**Comment by fjaguero** [comment]
Ok, en breve le doy un toque.

**Comment by nukeador** [comment]
Sí, hay gente que nos ha dicho que no se ha enterado, ve los foros cerrados y si no se para a mirar ni se da cuenta del mensaje arriba.

**Comment by fjaguero** [comment]
Ya está el PR https://github.com/mozillahispano/mozilla-hispano.org/pull/239 @stripTM
