### ISSUE TITLE
Nuevo plugin WP

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#236]
Hola,

Necesitamos instalar este plugin:

https://github.com/discourse/wp-discourse

Gracias.

**Comment by fjaguero** [comment]
Ok, me lo asigno

**Comment by nukeador** [comment]
Está instalado y activo en prod.

Importar importa bien porque he hecho la prueba activándolo en:

http://www.mozilla-hispano.org/firebug-3-y-multiproceso-en-firefox-e10s/

Y se ha publicado correctamente en:

https://foro.mozilla-hispano.org/t/firebug-3-y-multiproceso-en-firefox-e10s/19521/1

¿Problema? Que en WP no se añade el código para mostrar los comentarios.

Sospecho que en nuestro template nos falta algún código de comentarios que usa el plugin para añadir el contenido después.

@fjaguero @stripTM ¿podéis mirarlo hoy? Yo he hecho pruebas y no doy con ello.

Como referencia, esto es lo que hace el plugin:

https://github.com/discourse/wp-discourse/blob/master/lib/discourse.php

**Comment by nukeador** [comment]
He logrado que salgan, el problema era ese que el template no tenía un div comments y no lo enganchaba. Ahora me falta el css.

**Comment by nukeador** [comment]
Bueno, ya tenemos el css. A ver cómo se comporta cuando haya bastantes mensajes.
