### ISSUE TITLE
Quitar items de barra lateral

### ISSUE THREAD

**Issue by juaneladio** [mozillahispano/mozilla-hispano.org#263]
Hola, en la actual web de Mozilla Hispano, al lado de la lista de artículos se muestran varios enlaces, algunos de los cuales ya dejaron de ser vigentes.

Propongo que se quiten los enlaces a Firefox Flicks y Desafío para desarrolladores.

**Comment by fjaguero** [comment]
Me lo asigno para hacer el PR, ¿cómo lo ven los demás?

**Comment by fjaguero** [comment]
Por cierto, mi +1 para ello. Todo lo que está deprecated hay que ir sacándolo.

**Comment by stripTM** [comment]
+1, no tiene sentido mantenerlos.

**Comment by fjaguero** [comment]
Ya está quitado.
