### ISSUE TITLE
Tabzilla se sobrepone a la notificación que aparece al crear un nuevo tema en el foro

### ISSUE THREAD

**Issue by mautematico** [mozillahispano/mozilla-hispano.org#273]
Al crear un nuevo tema en el foro de mozilla hispano, tabzilla se sobrepone a la notificación amarilla que da algunas sugerencias sobre la creación de temas, ocasionando que el logo de mozilla hispano y varios elementos del menú de tabzilla queden encima.

Adjunto una imagen.

![ee1aeee54a5bdf66f1ae46824209264a5fc9b293](https://cloud.githubusercontent.com/assets/1238928/8379502/16d30b18-1be6-11e5-99c3-46b818d5fbc2.png)

**Comment by fjaguero** [comment]
¿Cómo puedo reproducir el que salga la barra de tips amarilla?

**Comment by fjaguero** [comment]
Ping @mautematico

**Comment by mautematico** [comment]
@fjaguero, solía aparecerme *siempre* al crear un nuevo hilo. Esta noche intentaré ofrecerte pasos detallados. :)

**Comment by fjaguero** [comment]
Lo acabo de ver, es porque tiene el tullido un z-index: 1 y main un z-index: 0. Lo pasaré a z-index 2, ya que no hay nada con lo que tenga conflicto según veo.

**Comment by fjaguero** [comment]
Lo iba a mirar de nuevo para cerrarlo y no recuerdo como hice para reproducirlo, quizás @nukeador da un tip.

**Comment by nukeador** [comment]
Tiene que ser algo de z-index de la caja de redacción. Si haces la ventana muy pequeña a lo alto puedes ver el comportamiento.

**Comment by fjaguero** [comment]
Ya está identificado. Voy a mirar el log de ese CSS para ver por qué se mete un z-index 0 a #main, ya que quitándolo y poniendo un z-index a la caja del mensaje se soluciona.
