### ISSUE TITLE
Entradas pendientes

### ISSUE THREAD

**Issue by francjp** [mozillahispano/mozilla-hispano.org#275]
Sorry si estoy duplicando, pero no encuentro el Issue ahora mismo.
Tenemos 11.591 entradas pendientes en el dashboard del WP... o vamos borrando de a 20, o no sé si habrá alguna manera de hacer una migración de todas esas entradas.

Hoy he estado borrando las que había en papelera, y borradores antiguos (más de 6 meses). Pero tenemos un pequeño caos en el dashboard.

**Comment by francjp** [comment]
Buenas,

Estoy viendo que hay un plugin que quizás nos podría ayudar:
http://ayudawp.com/borrar-entradas-en-lote-pero-de-verdad/

No sé si se puede instalar para terminar de borrar las entradas pendientes que tenemos.

Saludos,

**Comment by fjaguero** [comment]
Le echo un ojo y lo instalo si lo necesitas.

**Comment by francjp** [comment]
Ok, avisame para no seguir borrando a mano... que es un poco aburrido :P

**Comment by fjaguero** [comment]
Ok, son todas las que están como pendientes o alguna no?

**Comment by fjaguero** [comment]
@francjp Ya está instalado. Según el plugin hay 8788 pendientes. ¿Le das?

**Comment by francjp** [comment]
Hay más pendientes... pero bueno, lo miro, reviso y me las cargo ;)

Gracias
