### ISSUE TITLE
Revisión de autores en WP

### ISSUE THREAD

**Issue by francjp** [mozillahispano/mozilla-hispano.org#276]
Buenas,

Estoy viendo que tenemos muchos usuarios inactivos en el WP. Necesitaría revisar quiénes siguen editando y borrar (o poner sólo como "suscritpor").

Sumado a ello, hay 7 administradores... no sé si reducirlos o dejarlo como está.

**Comment by nukeador** [comment]
Con que dejes al equipo técnico y a @fjaguero como admins para tareas de mantenimiento, el resto de usuarios déjalos como necesitéis en noticias.

**Comment by francjp** [comment]
Ok... voy a dejar a un par más de admin y luego reviso el resto

**Comment by stripTM** [comment]
Yo no estoy como admin

**Comment by francjp** [comment]
@stripTM te vuelvo a poner como admin??, tienes casi los mismos permisos, menos 2 o 3 cosas

**Comment by francjp** [comment]
en realidad, no sé quién del equipo técnico debería ir:
- Rubén
- Fer agüero
- Willy?
- Fer??

Me estoy olvidando de alguien??

**Comment by fjaguero** [comment]
No que yo sepa

**Comment by nukeador** [comment]
Equipo técnico: Willyaranda, stripTM y yo.
Webdev: Fjaguero.

**Comment by fjaguero** [comment]
Ya lo tenés @francjp? :smile:

**Comment by francjp** [comment]
Por supuesto webdev ;)

**Comment by fjaguero** [comment]
Cerramos entonces?
