### ISSUE TITLE
Problema con inicio de sesión con persona

### ISSUE THREAD

**Issue by Emmanuel00** [mozillahispano/mozilla-hispano.org#287]
En ocasiones cuando se trata de iniciar con persona en el foro no detecta la cuenta ni se recarga la página para iniciar sesión..

**Comment by fjaguero** [comment]
¿Alguna forma de reproducirlo?

**Comment by Emmanuel00** [comment]
si
1. Entras a https://foro.mozilla-hispano.org/
2. Haces clic en "iniciar sesión"
3. En la "ventana" que te sale haces clic en "persona"
4. Escribes tu correo y esperas a que "persona" de lo verifique
5. Escribes tu coontraseña debido a que firefox no te la autocompleta (https://bugzilla.mozilla.org/show_bug.cgi?id=1200933)
5. Esperas......, la  página no se actualizara iniciandote sesión, o si ti la actualizas tampoco te habra iniciado sesión
Nota: No siempre ocurre, en ocasiones la sesión si se inicia, en ocasiones no, y las pruebas que hice fueron en firefox 40, y en microsoft edge, dando los mismos resultados

**Comment by pochy-ja** [comment]
A mi me pasa también, me ocurre en firefox 40.0.3 GNU/Linux, es a veces, no siempre, un indicador puede ser que siempre me pasa es cuando tengo muchas pestañas abiertas!

**Comment by fjaguero** [comment]
Probaré con un perfil limpio para ver si lo puedo reproducir.
