### ISSUE TITLE
Los márgenes de los artículos de portada son incorrectos en la vista mobile

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/mozilla-hispano.org#291]
Debería haber más padding a los lados.

![Screen](http://cl.ly/image/2p3b19330c25/Image%202015-09-15%20at%2011.02.14%20p.%20m..png)

**Comment by stripTM** [comment]
Tenemos demasiadas reglas con !important

**Comment by parguello** [comment]
@fjaguero este problema parece que a dia de hoy no se reproduce.
Yo veo bien los márgenes para el contenido de noticias de la página principal.
Desde el móvil el margen es igual a ambos lados.
Crees que sería necesario aumentarlo?

**Comment by fjaguero** [comment]
Idealmente el layout debería cambiar para que realmente se pueda leer bien en móvil: mover la imagen, no justificar así el texto, etc, pero sí, debería estar igualado y con un poco más. Lo dejo cerrado entonces para crear otro en ese caso.
