### ISSUE TITLE
entrada de noticias en discourse no muestra URL completa

### ISSUE THREAD

**Issue by pochy-ja** [mozillahispano/mozilla-hispano.org#295]
Me entero de la noticias publicadas mediante los correo que me envía discourse, pero hace unas cuantas, no está mostrando la noticia completa del enlace en el cuerpo de correo y accediendo al discourse veo que allí se muestra igual, aunque si apunta a la noticia pero lo que se ve es solo el dominio del sitio, sería esto un error?, adjunto una captura. Quisas se pueda mostrar el titulo de la noticia en vez del enlace como se hacía anteriormente.

![discuorse-enlace](https://cloud.githubusercontent.com/assets/7938214/11135626/e0b95954-8974-11e5-98b7-d654ce497510.png)

**Comment by nukeador** [comment]
Esto es porque discourse intenta hacer una vista previa de enlace, y por algún motivo nuestro Wordpress no da esa información.

Deberíamos arreglar nuestro theme para que de esa información via oEmbed o Open Graph, el theme por defecto de WP lo hace:

http://oembed.com/
https://developers.facebook.com/docs/sharing/opengraph

@stripTM @fjaguero

**Comment by stripTM** [comment]
¿Eso antes funcionaba y ahora se ha perdido? ¿O nunca ha funcionado y hay que añadir esa info a los templates?

**Comment by pochy-ja** [comment]
Antes funcionaba, siempre me llegaron por correo y se veía el enlace completo del artículo publicado, mi recomendación es que se pudiera poner el título del artículo o dejarlo como estaba antes!

**Comment by pochy-ja** [comment]
Un poco más allá estado mirando por el theme y los plugin, a no ser que hayan hecho algun cambio en el theme, lo que se me ocurre es que haya sido introducido por la actualización de wordpress, de todas maneras he visto que la versión del plugin de discourse es la 0.6.3 y está fuera ya la 0.6.4 en el README y 0.6.6 en los commits, pueden probar actualizar el plugin haber si se soluciona.

**Comment by nukeador** [comment]
Aclarar que no hemos cambiado nada, yo creo que es que simplemente discourse ahora lo muestra así y no podemos hacer nada excepto solucionar que el blog de la meta-data que debería dar para que se muestre bien.

**Comment by pochy-ja** [comment]
Que han hecho para corregirlo?, a partir de esta noticia[1] sale bien, si embargo en la noticia anterior[2] que fue hace 2 días salía con este problema, quisás sea algo desde la publicación de la noticia, @yuniers algo que se te ocurra!

**Comment by nukeador** [comment]
Uhmmm, toque en la config que mozilla-hispano.org no fuera dominio que usara onebox, pero ¿parece que no afectó a anteriores temas?

**Comment by pochy-ja** [comment]
No, es que al parecer se hace cuando se crea la noticia en discourse, por los que las noticias que ya salieron mal así se quedan, pero ya salen bien las nuevas noticias, por lo que para mí esto a quedado solucionado!
