### ISSUE TITLE
Errores PHP visibles en Planet

### ISSUE THREAD

**Issue by yondemon** [mozillahispano/mozilla-hispano.org#296]
Quizá habéis cambiado de versión de PHP... y esto ha roto un poco:
https://www.mozilla-hispano.org/planet/

**Comment by stripTM** [comment]
Gracias por el aviso, lo reviso.

**Comment by stripTM** [comment]
Pues parece que con la nueva versión de php, o por cambios en los API de twitter, flickr y el gestor de rss se nos han quedado obsoletas las bibliotecas que teníamos y ahora no recuperan nada.

Ya no aparecen los errores pero la página está inservible, abro issue https://github.com/mozillahispano/mozilla-hispano.org/issues/297
