### ISSUE TITLE
Perfil - Validar las extensiones de "Fondo de Perfil" y "Fondo de Tarjeta de Usuario".

### ISSUE THREAD

**Issue by ilse-macias** [mozillahispano/mozilla-hispano.org#303]
Permite subir archivos en PDF, el cuál no veo ninguna imagen.
Debería permitir los archivos **jpg, jpeg, png, gif, bmp**

**Comment by stripTM** [comment]
No entiendo lo que comentas que no permite subir jpg, jpeg, png, gif y bmp.

Acabo de subir fotos en jpg para mi fondo de perfil y el de la tarjeta de usuario sin problema.

**Comment by ilse-macias** [comment]
Perdón, no escribí correctamente el error.

Lo que no debería es el PDF, no le veo sentido ¿ni modo que muestre un PDF de 200 hojas? ¿Cuál es el objetivo?

> Debería permitir los archivos jpg, jpeg, png, gif, bmp

 Esa última extensión (**bmp**) no me permite subirla, acabo de hacer otra prueba y me sale un alert de error.

**Comment by nukeador** [comment]
Discourse define las extensiones permitidas de forma global, no se puede cambiar solo para las imágenes de perfil.

Esto es lo que hay ahora mismo configurado

![extensions](https://cloud.githubusercontent.com/assets/531906/12904246/389aa9fe-cece-11e5-8af8-0ee017c7dcca.png)

El no permitir bpm es intencionado, es un formato sin compresión que ocupa demasiado.
