### ISSUE TITLE
Perfil - Alert de error al subir una imagen.

### ISSUE THREAD

**Issue by ilse-macias** [mozillahispano/mozilla-hispano.org#304]
El alert cuando se sube una imagen con una extensión no permitida, muestra el siguiente error:

> Lo sentimos, el archivo que intenta cargar no está autorizado (authorized: jpg, jpeg, png, gif, pdf).

Lo cuál no es correcto por mezclar dos idiomas cual el foro es en español. El mensaje de error debería decir así:

> El error debe decir: "Lo sentimos, el archivo que intenta cargar no está autorizado. Las extensiones permitidas son: jpg, jpeg, png, gif, bmp.

**Comment by nukeador** [comment]
Hola Ilsa,

Gracias por avisar.

En este caso, esto depende de la traducción de Discourse, la cual es externa a nosotros:

https://www.transifex.com/discourse/discourse-org/

Se podría ayudar a tenerla al día si tenemos gente interesada y las cadenas se actualizarían al actualizar el foro.

Un saludo.
