### ISSUE TITLE
Redes sociales. Abrir una nueva pestaña al dar click en cualquier botón de redes sociales.

### ISSUE THREAD

**Issue by ilse-macias** [mozillahispano/mozilla-hispano.org#305]
Como sugerencia y buenas técnicas de tester.

Al dar click en un botón de redes sociales (eg. Google+) estando en una página por ejemplo https://www.mozilla-hispano.org/mx/ me redirecciona dentro de la tab https://plus.google.com/+mozillahispano/posts y saca al usuario de la página de Firefox; lo cual se dice que no es correcto por que al usuario "pierde la atención" de su objetivo, por eso es recomendable en una nueva tab.

**Comment by nukeador** [comment]
Por usabilidad ese comportamiento es el estándar, no abrir una nueva pestaña al usuario.

Referencia: http://ux.stackexchange.com/questions/19892/opening-website-external-links-in-new-window-published-usability-tests
