### ISSUE TITLE
Aumentar el tamaño de la fuente al redactar

### ISSUE THREAD

**Issue by pochy-ja** [mozillahispano/mozilla-hispano.org#318]
Como comentaba [por acá en el foro](https://foro.mozilla-hispano.org/t/cambio-del-nombre-de-la-categoria/22370/3), si fuera posible subir un poco el tamaño de la fuente por defecto a la hora de redactar las respuestas en el foro, al menos al tamaño de como está en el de inglés, se agradecería.

Saludos

![font](https://cloud.githubusercontent.com/assets/7938214/15095685/8e048468-14a2-11e6-81f7-c5f3e322dbc2.png)

**Comment by stripTM** [comment]
Lo he subido un poco el tamaño, a ver que te parece.

**Comment by pochy-ja** [comment]
Gracias, para mí a quedado bien!
