### ISSUE TITLE
Limpieza de issues

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/mozilla-hispano.org#337]
Estaba viendo que tenemos mucho issues abiertos. Muchos no se harán porque ya son antiguos, y otros tampoco son tan relevantes y hacen que se pierda un poco el foco, dado que son cambios complejos que al final no aportan tanto. Estaba pensando en cerrar gran parte de ellos, y así solo abrir y mantener siempre un máximo de 5-6. ¿Cómo lo ven @mozillahispano/tecnico?

**Comment by nukeador** [comment]
@stripTM estaba mirando un theme con el nuevo style, lo que haría que la mayoría de issues esté obsoleto

**Comment by fjaguero** [comment]
Sí, lo cual tiene sentido. ¿Me pasas el link @stripTM?

**Comment by stripTM** [comment]
Este es el de discourse: https://github.com/mozilla/discourse-mozilla-theme y no recuerdo si existía el de wordpress.

Lo que he hecho es levantar stage, pero la base de datos es la de producción, mi idea es clonarla de manera que stage sea un clon de producción y poder probar tranquilamente

**Comment by nukeador** [comment]
Buscando creo que el de WP es este:

https://github.com/craigcook/frontierline-theme

Que usan en http://blog.nightly.mozilla.org/

**Comment by parguello** [comment]
No se si ya esta reportado, pero he visto que el slider de la pagina principal no se esta mostrando:
<div class="home" id="content-bar">
			[orbit-slider]	</div>

**Comment by fjaguero** [comment]
Gracias por el reporte @parguello. Lo he creado en #348.
