### ISSUE TITLE
Página Firefox OS

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozilla-hispano.org#34]
Queremos crear una página que sea un recopilatorio con información de todas las áreas sobre Firefox OS.

Abro issue para no perderlo de vista, pero hace tiempo que no tenemos más sugerencias:

https://mozhispano.etherpad.mozilla.org/fxos-landing

**Comment by Gary-Flores** [comment]
Hola soy nuevo y tengo 2 preguntas, una es puedo reutilizar parte de el cogigo y armar un nuevo diseño, y lo de los colores no le entendi muy bien que preservar o hacer algun cambio radical, estare trabajando en eso, ya luego participo nuevamente con una propuesta de pagina.

**Comment by fjaguero** [comment]
Hola @Gary-Flores. Habría que abrir un hilo en el foro de Labs para comentarlo y ver las prioridades.

**Comment by KevinLoaiza** [comment]
Puedo apoyar en la recopilación y publicación de información, sólo ocupo que me compartan los links. No sé si ya se tienen recopilados en algún sitio o blog de notas, pues a lo que he visto, hay bastantes sitios. 

Preguntas:
1.- ¿La información recopilada debe trasladarse de manera literal, sintetizada o tipo RSS?
2.- ¿Ya existe dicha página?
3.- En dado caso de que no exista, puede comenzarse con WP, como comenta @nukeador. Creo el principal objetivo sería "Recopilar la información". Después de ven cuestiones de estética y personalización.

**Comment by fjaguero** [comment]
@KevinLoaiza Este proyecto no se priorizó, ya que se están haciendo otras iniciativas (sobre todo por la parte del Blog de Labs) para promover Firefox OS. Son otras acciones menos costosas y más realistas para los recursos con los que contamos. Lo voy a cerrar y volver a abrirlo cuando se considere @nukeador.
