### ISSUE TITLE
El foro no registra que tengo Windows 8

### ISSUE THREAD

**Issue by xXNeioXx** [mozillahispano/mozilla-hispano.org#42]
Pues como dice el título, tengo Windows 8 y el foro registra y muestra que tengo Windows 7, por lo tanto aquellos usuarios que tengan Windows 8 y no lo digan será más difícil ayudarlos, básicamente es lo mismo y a mi no me ha dado problemas pero varios usuarios ya han marcado que si y que lo implementaran sería genial :D

**Comment by nukeador** [comment]
El foro phpbb está jubilado. Cierro.
